devsearch/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('projects.urls')),
    path('users/',include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import profiles,userProfile,loginUser,logoutUser,registerUser

urlpatterns = [
    path('login/',loginUser,name="login"),
    path('logout/',logoutUser,name="logout"),
    path('register/',registerUser,name="register"),
    path('',profiles,name="profiles"),
    path('profile/<str:pk>',userProfile,name="user-profile"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.
class Project(models.Model):
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE,blank=True,null=True)
    title = models.CharField(max_length=255)
    description = models.TextField(null=True,blank=True)
    feature_image = models.ImageField(null=True,blank=True,default="icon.svg")
    demo_link = models.CharField(max_length=2000)
    source_link =  models.CharField(max_length=2000)
    tags = models.ManyToManyField('Tag',blank=True)
    vote_total = models.IntegerField(default = 0, null= True, blank = True)
    vote_ratio = models.IntegerField(default = 0, null= True, blank = True)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key = True, editable = False)

    def __str__(self):
        return self.title
    
class Review(models.Model):
    VOTE_TYPE = (
        ('up',"UP Vote"),
        ('down',"Down Vote")
    )
    owner = models.ForeignKey(Profile,null=True,blank=True,on_delete=models.CASCADE)
    project = models.ForeignKey(Project,on_delete = models.CASCADE)
    body = models.TextField(null=True, blank = True)
    value = models.CharField(max_length = 200,choices = VOTE_TYPE)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key = True, editable = False)
    
    def __str__(self):
        return self.value
    

class Tag(models.Model):
    name = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key = True, editable = False)

    def __str__(self):
        return self.name    

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=255,blank=True,null=True)
    email = models.EmailField(max_length=500,blank=True,null=True)
    username = models.CharField(max_length=255,blank=True,null=True)
    location = models.CharField(max_length=255,blank=True,null=True)
    short_intro = models.CharField(max_length=255,blank=True,null=True)
    bio = models.TextField(blank=True,null=True)
    profile_picture = models.ImageField(null=True,blank=True,upload_to="profiles/",default="profiles/user-default.png")
    social_github = models.CharField(max_length=255,blank=True,null=True)
    social_twitter = models.CharField(max_length=255,blank=True,null=True)
    social_linkedin = models.CharField(max_length=255,blank=True,null=True)
    social_youtube = models.CharField(max_length=255,blank=True,null=True)
    social_website = models.CharField(max_length=255,blank=True,null=True)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key = True, editable = False)

    def __str__(self):
        return str(self.user.username)

class Skills(models.Model):
    owner = models.ForeignKey(Profile,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=255,blank=True,null=True)
    description = models.TextField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add = True)
    id = models.UUIDField(default = uuid.uuid4, unique = True, primary_key = True, editable = False)

    def __str__(self):
        return self.name
    

users/views.py
from django.shortcuts import redirect, render
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout
from django.contrib import messages
from .froms import CustomUserCreationForm
# Create your views here.
def loginUser(request):
    page = 'login'
    context = {'page':page}
    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request, "Username does not exist")
        user = authenticate(request,username = username,password = password)
        if user is not None:
            login(request,user)
            return redirect('profiles')
        else:
            messages.error(request, "username or password is incorrect")
    return render(request,"users/login_registrer.html")

def logoutUser(request):
    logout(request)
    messages.info(request, "User successfully logged out")
    return redirect('login')

def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request,"Account was created")
            login(request,user)
            return redirect('profiles')
        else:
            messages.error(request,"An error was occurred during registration")
    context = {'page':page,'form':form}
    return render(request,"users/login_registrer.html",context)

def profiles(request):
    profiles = Profile.objects.all()
    context = {'profiles':profiles}
    return render(request,"users/profiles.html",context)

def userProfile(request,pk):
    user = Profile.objects.get(id=pk)
    topSkills = user.skills_set.exclude(description__exact = "")
    otherSkills = user.skills_set.filter(description = "")
    context = {'profile':user,"topSkills":topSkills,"otherSkills":otherSkills}
    return render(request,"users/user-profile.html",context)

users/templates/users/login_registrer.html
{% extends 'main.html' %}
{% load static %}


{% block content %}
    
    {% if page == "register" %}
        <div class="auth">
            <div class="card">
              <div class="auth__header text-center">
                <a href="/">
                  <img src="{% static 'images/icon.svg' %}" alt="icon" />
                </a>
                <h3>Account SignUp</h3>
                <p>Create a new developer account</p>
              </div>
      
              <form action="{% url 'register' %}" method="post" class="form auth__form">
                {% csrf_token %}
                <!-- Input:Text -->
                
                {% for field in form %}
                    <div class="form__field">
                        <label for="formInput#text">{{field.label}} </label>
                        {{field}}
                        {% for error in field.errors %}
                            <p style="color: red;">{{error}}</p>
                        {% endfor %}
                            
                            
                    </div>    
                {% endfor %}
                <div class="auth__actions">
                  <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
                </div>
              </form>
              <div class="auth__alternative">
                <p>Already have an Account?</p>
                <a href="{% url 'login' %}">Log In</a>
              </div>
            </div>
          </div>
    {% else %}
        <div class="auth">
            <div class="card">
              <div class="auth__header text-center">
                <a href="/">
                  <img src="{% static 'images/icon.svg' %}" alt="icon" />
                </a>
                <h3>Account Login</h3>
                <p>Hello Developer, Welcome Back!</p>
              </div>
      
              <form action="{% url 'login' %}" method="post" class="form auth__form">
                {% csrf_token %}
                <!-- Input:Email -->
                <div class="form__field">
                  <label for="formInput#text">Username: </label>
                  <input
                    class="input input--text"
                    id="formInput#text"
                    type="text"
                    name="username"
                    placeholder="Enter your username..."
                  />
                </div>
      
                <!-- Input:Password -->
                <div class="form__field">
                  <label for="formInput#password">Password: </label>
                  <input
                    class="input input--password"
                    id="formInput#passowrd"
                    type="password"
                    name="password"
                    placeholder="••••••••"
                  />
                </div>
                <div class="auth__actions">
                  <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
                  <a href="forgetpassword.html">Forget Password?</a>
                </div>
              </form>
              <div class="auth__alternative">
                <p>Don’t have an Account?</p>
                <a href="{% url 'register' %}">Sign Up</a>
              </div>
            </div>
        </div>      
    {% endif %}
    
{% endblock content %}
    

users/templates/users/profiles.html
{% extends 'main.html' %}


{% block content %}

    <!-- Main Section -->
  <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          
          {% for profile in profiles %}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user-profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{profile.profile_picture.url}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{profile.bio|slice:"150"}}
                </p>
                <div class="dev__skills">
                  
                  {% for skill in profile.skills_set.all %}
                    <span class="tag tag--pill tag--main">
                      <small>{{skill}}</small>
                    </span>
                  {% endfor %}
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </section>
  </main>
    
{% endblock content %}
    

users/templates/users/user-profile.html
{% extends 'main.html' %}


{% block content %}

<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_picture.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                
                {% if profile.social_github %}
                  <li>
                    <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="fa-brands fa-github"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_youtube %}
                  <li>
                    <a title="Stackoverflow" href="{{profile.social_youtube}}" target="_blank"><i class="fa-brands fa-youtube"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_twitter %}
                  <li>
                    <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="fa-brands fa-twitter"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_linkedin %}
                  <li>
                    <a title="LinkedIn" href="{{profile.social_linkedin}}" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                  </li>
                {% endif %}
                {% if profile.social_website %}
                  <li>
                    <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="fa-solid fa-globe"></i></a>
                  </li>
                {% endif %}
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
              {% for skill in topSkills %}
                <div class="devSkill">
                  <h4 class="devSkill__title">{{skill.name}}</h4>
                  <p class="devSkill__info">
                    {{skill.description}}
                  </p>
                </div>
              {% endfor %}
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in otherSkills %}
                  <span class="tag tag--pill tag--sub tag--lg">
                    <small>{{skill.name}}</small>
                  </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
              
              {% for project in profile.project_set.all %}
                <div class="column">
                  <div class="card project">
                    <a href="{% url 'project' project.id %}" class="project">
                      <img class="project__thumbnail" src="{{project.feature_image.url}}" alt="project thumbnail" />
                      <div class="card__body">
                        <h3 class="project__title">{{project.title}}</h3>
                        <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                        <p class="project--rating">
                          <span style="font-weight: bold;">{{project.vote_ratio}}</span> Postitive
                      Feedback ({{project.vote_total}}) Vote{{project.vote_total|pluralize:"s"}}
                        </p>
                        <div class="project__tags">
                          {% for tag in  project.tags.all %}
                            <span class="tag tag--pill tag--main">
                              <small>{{tag}}</small>
                            </span>
                          {% endfor %}
                        </div>
                      </div>
                    </a>
                  </div>
                </div>
              {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
    
{% endblock content %}
    